name: WakAPI Stats
on:
  schedule: [{cron: "0 * * * *"}] # at every hour
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  wakapi-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKAPI_TOKEN }}
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_limit: 0
          plugin_wakatime_url: ${{ secrets.WAKAPI_URL }}
          plugin_wakatime_user: krisjanis2000
